# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g @angular/cli
    - run: npm install
    - run: ng build --configuration production
    - name: Checkout Latest Repo
      uses: actions/checkout@master
    - name: Generate Deployment Package 
      run: zip -r deploy.zip * -x "**node_modules**"
    - name: Deploy to EB
      uses: aws-actions/aws-elasticbeanstalk-deploy@v1
      with:
           environment-name: Angularebs-env
           application-name: angular
           deployment-package: deploy.zip
           region: us-east-1
           version-label: "the-Angularebs-deployment-${{ steps.format-time.outputs.replaced }}"
           access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path: node_modules
